commerce_shipping.commerce_shipping_method.plugin.ups:
  type: commerce_shipping_method_configuration
  mapping:
    api_information:
      label: 'API information'
      type: mapping
      mapping:
        account_number:
          type: string
          label: 'Account number'
        mode:
          type: boolean
          label: 'Choose whether to use test or live mode'
        client_id:
          type: string
          label: 'Client ID'
        secret:
          type: string
          label: 'Client secret'
    rate_options:
      type: mapping
      label: 'UPS Rating Options'
      mapping:
        rate_type:
          type: boolean
          label: 'Choose whether to use negotiated or standard rates'
    options:
      type: mapping
      label: 'UPS Options'
      mapping:
        tracking_url:
          type: string
          label: 'Tracking URL'
        log:
          type: mapping
          label: 'Log the following messages for debugging'
          mapping:
            request:
              type: boolean
              mapping:
                value:
                  label: 'API request messages'
            response:
              type: boolean
              mapping:
                value:
                  label: 'API response messages'
